import { Agent } from '@/types';
import { v4 as uuidv4 } from 'uuid';

export const DEFAULT_AGENTS: Agent[] = [
  {
    id: uuidv4(),
    name: '战略家 Atlas',
    role: 'strategist',
    provider: 'kimi',
    model: 'kimi-k2-0711-preview',
    apiKey: '',
    color: '#3b82f6',
    avatar: '🎯',
    enabled: true,
  },
  {
    id: uuidv4(),
    name: '批判者 Socrates',
    role: 'critic',
    provider: 'glm',
    model: 'glm-z1-plus',
    apiKey: '',
    color: '#8b5cf6',
    avatar: '🔍',
    enabled: true,
  },
  {
    id: uuidv4(),
    name: '创新者 Tesla',
    role: 'innovator',
    provider: 'minimax',
    model: 'MiniMax-Text-01',
    apiKey: '',
    color: '#10b981',
    avatar: '💡',
    enabled: true,
  },
  {
    id: uuidv4(),
    name: '执行者 Hermes',
    role: 'executor',
    provider: 'qwen',
    model: 'qwen3-235b-a22b',
    apiKey: '',
    color: '#f59e0b',
    avatar: '⚡',
    enabled: true,
  },
  {
    id: uuidv4(),
    name: '主持人 Themis',
    role: 'moderator',
    provider: 'deepseek',
    model: 'deepseek-chat',
    apiKey: '',
    color: '#06b6d4',
    avatar: '⚖️',
    enabled: true,
  },
];
