import { Agent } from '@/types';
import { v4 as uuidv4 } from 'uuid';

export const DEFAULT_AGENTS: Agent[] = [
  {
    id: uuidv4(),
    name: '战略家 Atlas',
    role: 'strategist',
    provider: 'openai',
    model: 'gpt-4o',
    apiKey: '',
    color: '#6366f1',
    avatar: '🎯',
    enabled: true,
  },
  {
    id: uuidv4(),
    name: '批判者 Socrates',
    role: 'critic',
    provider: 'anthropic',
    model: 'claude-sonnet-4-6',
    apiKey: '',
    color: '#ef4444',
    avatar: '🔍',
    enabled: true,
  },
  {
    id: uuidv4(),
    name: '创新者 Tesla',
    role: 'innovator',
    provider: 'google',
    model: 'gemini-1.5-pro',
    apiKey: '',
    color: '#10b981',
    avatar: '💡',
    enabled: true,
  },
  {
    id: uuidv4(),
    name: '执行者 Hermes',
    role: 'executor',
    provider: 'openai',
    model: 'gpt-4o-mini',
    apiKey: '',
    color: '#f59e0b',
    avatar: '⚡',
    enabled: true,
  },
  {
    id: uuidv4(),
    name: '主持人 Themis',
    role: 'moderator',
    provider: 'anthropic',
    model: 'claude-sonnet-4-6',
    apiKey: '',
    color: '#8b5cf6',
    avatar: '⚖️',
    enabled: true,
  },
];
